name = "brazuca-fc-groningen"
compatibility_date = "2026-03-09"
pages_build_output_dir = "."

# Para desenvolvimento local com D1, substitua os placeholders abaixo.
[[d1_databases]]
binding = "DB"
database_name = "brazuca-fc-db"
database_id = "643a3e5c-8c8a-4f73-801d-026ce4492af4"
